/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Returns an access token in the body and a refresh token in an httpOnly cookie. */
    post: operations['authLogin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Blacklist the refresh token and clear the cookie. */
    post: operations['authLogout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['authMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** @description Marks onboarding complete. No other field is writable here. */
    patch: operations['authMeUpdate']
    trace?: never
  }
  '/api/auth/password/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['authPasswordChange']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/refresh/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Mint a new access token from the refresh cookie.
     *
     *     The token is read from the cookie, falling back to the body so the endpoint
     *     is still usable from a non-browser client.
     */
    post: operations['authRefresh']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/register/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Create the account, its profile, and hand back tokens.
     *
     *     Registration returns tokens so the user lands straight in the app rather than
     *     being bounced to a login form they just filled in.
     */
    post: operations['authRegister']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Service health: database connectivity and last successful run age. */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description The user's own job list.
     *
     *     Never `UserJob.objects.get(pk=...)` without a user filter — `get_object`
     *     resolves against the filtered queryset, so an id belonging to somebody else
     *     simply is not there.
     */
    get: operations['jobsList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description The user's own job list.
     *
     *     Never `UserJob.objects.get(pk=...)` without a user filter — `get_object`
     *     resolves against the filtered queryset, so an id belonging to somebody else
     *     simply is not there.
     */
    get: operations['jobsRetrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * @description The user's own job list.
     *
     *     Never `UserJob.objects.get(pk=...)` without a user filter — `get_object`
     *     resolves against the filtered queryset, so an id belonging to somebody else
     *     simply is not there.
     */
    patch: operations['jobsPartialUpdate']
    trace?: never
  }
  '/api/jobs/bulk_status/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Set one status across many jobs. Ids belonging to another user are ignored. */
    post: operations['jobsBulkStatusCreate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/statuses/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Human labels for every status, so the frontend never hardcodes them. */
    get: operations['jobsStatusesList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/locations/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description The cities offered in the onboarding picker.
     *
     *     Open to anonymous callers — the register screen needs it before there is a
     *     token to send.
     */
    get: operations['locationsList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/profile/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description The CURRENT USER's profile — never one identified by a client-supplied id. */
    get: operations['profileRetrieve']
    /** @description The CURRENT USER's profile — never one identified by a client-supplied id. */
    put: operations['profileUpdate']
    post?: never
    delete?: never
    options?: never
    head?: never
    /** @description The CURRENT USER's profile — never one identified by a client-supplied id. */
    patch: operations['profilePartialUpdate']
    trace?: never
  }
  '/api/profile/preview/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Score a hypothetical posting against the caller's own profile.
     *
     *     Tuning weights blind is miserable; this is what makes it interactive.
     */
    post: operations['profilePreview']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Run history.
     *
     *     Runs are global — they describe the shared fetch, not one user's data — so
     *     every authenticated user sees the same history. Nothing user-private is in
     *     them.
     */
    get: operations['runsList']
    put?: never
    /** @description Trigger a run. Returns 202 immediately; poll GET /api/runs/ for progress. */
    post: operations['runsCreate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Run history.
     *
     *     Runs are global — they describe the shared fetch, not one user's data — so
     *     every authenticated user sees the same history. Nothing user-private is in
     *     them.
     */
    get: operations['runsRetrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/sources/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Shared sources plus this user's own private ones.
     *
     *     Another user's private source is invisible: not listable, not readable, not
     *     editable, not deletable.
     */
    get: operations['sourcesList']
    put?: never
    /**
     * @description Shared sources plus this user's own private ones.
     *
     *     Another user's private source is invisible: not listable, not readable, not
     *     editable, not deletable.
     */
    post: operations['sourcesCreate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/sources/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Shared sources plus this user's own private ones.
     *
     *     Another user's private source is invisible: not listable, not readable, not
     *     editable, not deletable.
     */
    get: operations['sourcesRetrieve']
    /**
     * @description Shared sources plus this user's own private ones.
     *
     *     Another user's private source is invisible: not listable, not readable, not
     *     editable, not deletable.
     */
    put: operations['sourcesUpdate']
    post?: never
    /**
     * @description Shared sources plus this user's own private ones.
     *
     *     Another user's private source is invisible: not listable, not readable, not
     *     editable, not deletable.
     */
    delete: operations['sourcesDestroy']
    options?: never
    head?: never
    /**
     * @description Shared sources plus this user's own private ones.
     *
     *     Another user's private source is invisible: not listable, not readable, not
     *     editable, not deletable.
     */
    patch: operations['sourcesPartialUpdate']
    trace?: never
  }
  '/api/stats/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Dashboard summary for the requesting user.
     *
     *     Every count here is scoped to `request.user` except `last_run_at`, which
     *     describes the shared fetch.
     */
    get: operations['stats']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * @description * `not_started` - Not started
     *     * `researching` - Researching
     *     * `cv_tailored` - CV tailored
     *     * `applied` - Applied
     *     * `assessment` - Assessment
     *     * `interviewing` - Interviewing
     *     * `offer` - Offer
     *     * `rejected` - Rejected
     *     * `skipped` - Skipped
     * @enum {string}
     */
    ApplicationStatusEnum:
      | 'not_started'
      | 'researching'
      | 'cv_tailored'
      | 'applied'
      | 'assessment'
      | 'interviewing'
      | 'offer'
      | 'rejected'
      | 'skipped'
    BulkStatus: {
      ids: number[]
      status: components['schemas']['ApplicationStatusEnum']
    }
    /** @description A `UserJob` joined to its `Job`, flattened. */
    Job: {
      readonly id: number
      readonly key: string
      readonly source: string
      readonly company: string
      readonly title: string
      readonly location: string
      readonly url: string
      readonly description: string
      /** Format: date */
      readonly postedAt: string
      /** Format: date-time */
      readonly firstSeen: string
      /** Format: date-time */
      readonly lastSeen: string
      /** Format: date-time */
      readonly closedAt: string
      readonly seenCount: number
      readonly score: number
      readonly tier: string
      status?: components['schemas']['ApplicationStatusEnum']
      notes?: string
      pinned?: boolean
      readonly isNew: boolean
      readonly flags: unknown
      readonly detail: unknown
      readonly alsoSeenOn: unknown
      readonly dateFrom: string
      readonly trackingDays: number
    }
    /**
     * @description * `greenhouse` - Greenhouse
     *     * `lever` - Lever
     *     * `workable` - Workable
     *     * `breezy` - Breezy
     *     * `ashby` - Ashby
     *     * `smartrecruiters` - SmartRecruiters
     *     * `recruitee` - Recruitee
     *     * `workday` - Workday
     *     * `rss` - RSS / Atom
     *     * `jobspy` - Job boards (jobspy)
     * @enum {string}
     */
    KindEnum:
      | 'greenhouse'
      | 'lever'
      | 'workable'
      | 'breezy'
      | 'ashby'
      | 'smartrecruiters'
      | 'recruitee'
      | 'workday'
      | 'rss'
      | 'jobspy'
    /** @description A selectable city for the onboarding picker. */
    Location: {
      key: string
      label: string
      aliases: string[]
    }
    PaginatedJobList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null
      results: components['schemas']['Job'][]
    }
    PaginatedRunList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null
      results: components['schemas']['Run'][]
    }
    PaginatedSourceList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null
      results: components['schemas']['Source'][]
    }
    PaginatedStatusChoiceList: {
      /** @example 123 */
      count: number
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null
      results: components['schemas']['StatusChoice'][]
    }
    PasswordChange: {
      oldPassword: string
      newPassword: string
    }
    /** @description The only three fields a user may write. */
    PatchedJobUpdate: {
      status?: components['schemas']['ApplicationStatusEnum']
      notes?: string
      pinned?: boolean
    }
    /** @description The requesting user's own profile. `user` is never client-supplied. */
    PatchedProfile: {
      /** @description keyword → weight */
      skills?: unknown
      /** @description title term → multiplier */
      levelBonus?: unknown
      /** @description title term → multiplier */
      levelPenalty?: unknown
      titleBlocklist?: unknown
      locationsAllowed?: unknown
      locationsPreferred?: unknown
      locationsSecondary?: unknown
      /** Format: double */
      stackSaturation?: number
      freshness?: unknown
      roleKeywords?: unknown
      /** Format: date-time */
      readonly updatedAt?: string
    }
    /** @description A user sees shared sources and their own private ones, never another's. */
    PatchedSource: {
      readonly id?: number
      kind?: components['schemas']['KindEnum']
      slug?: string
      company?: string
      host?: string
      tenant?: string
      site?: string
      url?: string
      label?: string
      locationHint?: string
      config?: unknown
      enabled?: boolean
      /** Format: date-time */
      readonly lastRunAt?: string | null
      readonly lastStatus?: string
      readonly lastError?: string
      readonly isShared?: boolean
      readonly isMine?: boolean
    }
    /** @description The current user. Never exposes another user's row. */
    PatchedUser: {
      readonly id?: number
      /**
       * Email address
       * Format: email
       */
      readonly email?: string
      readonly onboardingComplete?: boolean
      /** Format: date-time */
      readonly dateJoined?: string
    }
    /** @description The requesting user's own profile. `user` is never client-supplied. */
    Profile: {
      /** @description keyword → weight */
      skills?: unknown
      /** @description title term → multiplier */
      levelBonus?: unknown
      /** @description title term → multiplier */
      levelPenalty?: unknown
      titleBlocklist?: unknown
      locationsAllowed?: unknown
      locationsPreferred?: unknown
      locationsSecondary?: unknown
      /** Format: double */
      stackSaturation?: number
      freshness?: unknown
      roleKeywords?: unknown
      /** Format: date-time */
      readonly updatedAt: string
    }
    /**
     * @description The refresh endpoint normally reads the httpOnly cookie.
     *
     *     The body field exists only so non-browser clients have a way in, and so the
     *     schema describes something concrete.
     */
    RefreshRequest: {
      refresh?: string
    }
    Register: {
      /** Format: email */
      email: string
      password: string
      /** @description Catalogue keys from GET /api/locations/. Defaults to Islamabad + Rawalpindi. */
      locations?: string[]
      /** @description Onboarding role chips that pre-weight the matching skills. */
      roleKeywords?: string[]
    }
    Run: {
      readonly id: number
      /** Format: date-time */
      startedAt?: string
      /** Format: date-time */
      finishedAt?: string | null
      status?: components['schemas']['RunStatusEnum']
      triggeredBy?: string
      sourcesTotal?: number
      sourcesFailed?: number
      postingsFetched?: number
      jobsCreated?: number
      jobsUpdated?: number
      jobsClosed?: number
      usersScored?: number
      error?: string
      /** Format: double */
      readonly durationSeconds: number | null
      readonly succeeded: boolean
    }
    /** @description Per-source results, so a partial failure is impossible to miss. */
    RunDetail: {
      readonly id: number
      /** Format: date-time */
      startedAt?: string
      /** Format: date-time */
      finishedAt?: string | null
      status?: components['schemas']['RunStatusEnum']
      triggeredBy?: string
      sourcesTotal?: number
      sourcesFailed?: number
      postingsFetched?: number
      jobsCreated?: number
      jobsUpdated?: number
      jobsClosed?: number
      usersScored?: number
      error?: string
      /** Format: double */
      readonly durationSeconds: number | null
      readonly succeeded: boolean
      readonly sourceResults: components['schemas']['RunSource'][]
    }
    RunSource: {
      readonly id: number
      label: string
      kind: string
      ok?: boolean
      postings?: number
      error?: string
      durationMs?: number
    }
    /**
     * @description * `running` - Running
     *     * `success` - Success
     *     * `partial` - Partial — some sources failed
     *     * `failed` - Failed
     * @enum {string}
     */
    RunStatusEnum: 'running' | 'success' | 'partial' | 'failed'
    /** @description A hypothetical posting, for tuning weights interactively. */
    ScorePreviewRequest: {
      /** @default  */
      title: string
      /** @default  */
      description: string
      /** @default  */
      location: string
      /** @default Preview */
      company: string
    }
    ScorePreviewResponse: {
      score: number | null
      tier: string | null
      detail: {
        [key: string]: unknown
      } | null
      flags: string[]
      filtered: boolean
      filteredReason: string | null
    }
    /** @description A user sees shared sources and their own private ones, never another's. */
    Source: {
      readonly id: number
      kind: components['schemas']['KindEnum']
      slug?: string
      company?: string
      host?: string
      tenant?: string
      site?: string
      url?: string
      label?: string
      locationHint?: string
      config?: unknown
      enabled?: boolean
      /** Format: date-time */
      readonly lastRunAt: string | null
      readonly lastStatus: string
      readonly lastError: string
      readonly isShared: boolean
      readonly isMine: boolean
    }
    Stats: {
      openCount: number
      newToday: number
      byTier: {
        [key: string]: number
      }
      bySource: {
        [key: string]: number
      }
      byStatus: {
        [key: string]: number
      }
      /** Format: double */
      avgScore: number | null
      /** Format: date-time */
      lastRunAt: string | null
      scoreHistogram: {
        [key: string]: unknown
      }[]
    }
    StatusChoice: {
      value: string
      label: string
    }
    TokenObtainPair: {
      email: string
      password: string
      readonly access: string
      readonly refresh: string
    }
    /** @description The current user. Never exposes another user's row. */
    User: {
      readonly id: number
      /**
       * Email address
       * Format: email
       */
      readonly email: string
      readonly onboardingComplete: boolean
      /** Format: date-time */
      readonly dateJoined: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  authLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenObtainPair']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  authLogout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  authMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  authMeUpdate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedUser']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  authPasswordChange: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChange']
      }
    }
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  authRefresh: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RefreshRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  authRegister: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Register']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  jobsList: {
    parameters: {
      query?: {
        company?: string
        /** @description e.g. ghost? */
        flag?: string
        /** @description Excludes inferred ages as well as nulls */
        has_date?: boolean
        include_closed?: boolean
        /** @description First appeared in this user's list on the last run */
        is_new?: boolean
        /** @description A location catalogue key */
        location?: string
        max_score?: number
        min_score?: number
        /** @description -score | posted_at | first_seen | company */
        ordering?: string
        /** @description A page number within the paginated result set. */
        page?: number
        pinned?: boolean
        /** @description Published today by the employer */
        posted_today?: boolean
        /** @description Published within the last N days */
        posted_within?: number
        /** @description Full-text over title, company, location */
        search?: string
        source?: string
        status?: string
        /** @description High | Medium | Stretch */
        tier?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedJobList']
        }
      }
    }
  }
  jobsRetrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this user job. */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Job']
        }
      }
    }
  }
  jobsPartialUpdate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this user job. */
        id: number
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedJobUpdate']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Job']
        }
      }
    }
  }
  jobsBulkStatusCreate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BulkStatus']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  jobsStatusesList: {
    parameters: {
      query?: {
        company?: string
        flag?: string
        has_date?: boolean
        include_closed?: boolean
        is_new?: boolean
        location?: string
        max_score?: number
        min_score?: number
        /** @description A page number within the paginated result set. */
        page?: number
        pinned?: boolean
        posted_today?: boolean
        posted_within?: number
        search?: string
        source?: string
        /**
         * @description * `not_started` - Not started
         *     * `researching` - Researching
         *     * `cv_tailored` - CV tailored
         *     * `applied` - Applied
         *     * `assessment` - Assessment
         *     * `interviewing` - Interviewing
         *     * `offer` - Offer
         *     * `rejected` - Rejected
         *     * `skipped` - Skipped
         */
        status?:
          | 'applied'
          | 'assessment'
          | 'cv_tailored'
          | 'interviewing'
          | 'not_started'
          | 'offer'
          | 'rejected'
          | 'researching'
          | 'skipped'
        tier?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedStatusChoiceList']
        }
      }
    }
  }
  locationsList: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Location'][]
        }
      }
    }
  }
  profileRetrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Profile']
        }
      }
    }
  }
  profileUpdate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['Profile']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Profile']
        }
      }
    }
  }
  profilePartialUpdate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedProfile']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Profile']
        }
      }
    }
  }
  profilePreview: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['ScorePreviewRequest']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ScorePreviewResponse']
        }
      }
    }
  }
  runsList: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedRunList']
        }
      }
    }
  }
  runsCreate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  runsRetrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this run. */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunDetail']
        }
      }
    }
  }
  sourcesList: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedSourceList']
        }
      }
    }
  }
  sourcesCreate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Source']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Source']
        }
      }
    }
  }
  sourcesRetrieve: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this source. */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Source']
        }
      }
    }
  }
  sourcesUpdate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this source. */
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Source']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Source']
        }
      }
    }
  }
  sourcesDestroy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this source. */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  sourcesPartialUpdate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description A unique integer value identifying this source. */
        id: number
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedSource']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Source']
        }
      }
    }
  }
  stats: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Stats']
        }
      }
    }
  }
}
