/**
 * Domain types, taken from the generated OpenAPI schema wherever possible.
 *
 * `schema.d.ts` is generated by `make gen-client` and committed, with a CI check
 * that it matches the backend. Aliasing here rather than importing the deep
 * generated paths everywhere keeps call sites readable and means a schema
 * reshuffle touches one file.
 */

import type { components } from './schema'

type Schemas = components['schemas']

export type User = Schemas['User']
export type Profile = Schemas['Profile']
export type Location = Schemas['Location']
export type Job = Schemas['Job']
export type Run = Schemas['Run']
export type RunDetail = Schemas['RunDetail']
export type Stats = Schemas['Stats']
export type Source = Schemas['Source']
export type ApplicationStatus = Schemas['ApplicationStatusEnum']

/** The DRF pagination envelope. The frontend expects this shape everywhere. */
export interface Paginated<T> {
  count: number
  next: string | null
  previous: string | null
  results: T[]
}

export interface AuthResponse {
  user: User
  access: string
}

export interface StatusChoice {
  value: ApplicationStatus
  label: string
}

/** The score breakdown. Every job carries one; a score with no reason is useless. */
export interface ScoreDetail {
  stack: number
  level: number
  location: number
  fresh: number
  skillsHit: string[]
  notes: string[]
  ageDays: number | null
  ageInferred: boolean
}

export interface ScorePreview {
  score: number | null
  tier: string | null
  detail: ScoreDetail | null
  flags: string[]
  filtered: boolean
  filteredReason: string | null
}

export const TIERS = ['High', 'Medium', 'Stretch'] as const
export type Tier = (typeof TIERS)[number]

/** Onboarding role chips. The values the backend accepts in `roleKeywords`. */
export const ROLE_KEYWORDS = [
  { value: 'dotnet', label: '.NET' },
  { value: 'react', label: 'React' },
  { value: 'angular', label: 'Angular' },
  { value: 'python', label: 'Python' },
  { value: 'qa', label: 'QA' },
  { value: 'devops', label: 'DevOps' },
  { value: 'ai_ml', label: 'AI / ML' },
] as const
