# Generated by Django 5.2.17 on 2026-08-15 19:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('workable', 'Workable'), ('breezy', 'Breezy'), ('ashby', 'Ashby'), ('smartrecruiters', 'SmartRecruiters'), ('recruitee', 'Recruitee'), ('workday', 'Workday'), ('rss', 'RSS / Atom'), ('jobspy', 'Job boards (jobspy)')], max_length=32)),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('posted_at', models.DateField(blank=True, null=True)),
                ('date_from', models.CharField(blank=True, max_length=32)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('also_seen_on', models.JSONField(blank=True, default=list)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('title', 'company', 'location', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
            ],
            options={
                'ordering': ('-last_seen',),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='job_search_vector'), models.Index(condition=models.Q(('closed_at__isnull', True)), fields=['-last_seen'], name='job_open_by_last_seen'), models.Index(fields=['source'], name='job_source'), models.Index(fields=['company'], name='job_company')],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('workable', 'Workable'), ('breezy', 'Breezy'), ('ashby', 'Ashby'), ('smartrecruiters', 'SmartRecruiters'), ('recruitee', 'Recruitee'), ('workday', 'Workday'), ('rss', 'RSS / Atom'), ('jobspy', 'Job boards (jobspy)')], max_length=32)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('tenant', models.CharField(blank=True, max_length=200)),
                ('site', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('location_hint', models.CharField(blank=True, max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null means shared with every user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kind', 'slug', 'label'),
                'indexes': [models.Index(fields=['enabled', 'kind'], name='source_enabled_kind'), models.Index(fields=['owner'], name='source_owner')],
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('tier', models.CharField(blank=True, max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('researching', 'Researching'), ('cv_tailored', 'CV tailored'), ('applied', 'Applied'), ('assessment', 'Assessment'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='not_started', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('first_seen_by_user', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_new', models.BooleanField(default=True)),
                ('tracking_days', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-score', '-first_seen_by_user'),
                'indexes': [models.Index(condition=models.Q(('is_open', True)), fields=['user', '-score'], name='userjob_open_by_score'), models.Index(fields=['user', 'status'], name='userjob_user_status'), models.Index(fields=['user', 'is_new'], name='userjob_user_is_new'), django.contrib.postgres.indexes.GinIndex(fields=['flags'], name='userjob_flags')],
                'constraints': [models.UniqueConstraint(fields=('user', 'job'), name='userjob_unique_user_job')],
            },
        ),
    ]
