# Generated by Django 5.2.17 on 2026-08-15 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial — some sources failed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('triggered_by', models.CharField(default='schedule', max_length=32)),
                ('sources_total', models.PositiveIntegerField(default=0)),
                ('sources_failed', models.PositiveIntegerField(default=0)),
                ('postings_fetched', models.PositiveIntegerField(default=0)),
                ('jobs_created', models.PositiveIntegerField(default=0)),
                ('jobs_updated', models.PositiveIntegerField(default=0)),
                ('jobs_closed', models.PositiveIntegerField(default=0)),
                ('users_scored', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['-started_at', 'status'], name='run_recent_by_status')],
            },
        ),
        migrations.CreateModel(
            name='RunSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=32)),
                ('ok', models.BooleanField(default=False)),
                ('postings', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_results', to='jobs.run')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_results', to='jobs.source')),
            ],
            options={
                'ordering': ('-ok', 'label'),
                'indexes': [models.Index(fields=['run', 'ok'], name='runsource_run_ok')],
            },
        ),
    ]
