# Generated by Django 5.2.17 on 2026-08-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_run_runsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
