# Generated by Django 5.2.17 on 2026-08-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_source_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
