# Generated by Django 5.2.17 on 2026-08-25 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJobStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('not_started', 'Not started'), ('researching', 'Researching'), ('cv_tailored', 'CV tailored'), ('applied', 'Applied'), ('assessment', 'Assessment'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], max_length=32)),
                ('to_status', models.CharField(choices=[('not_started', 'Not started'), ('researching', 'Researching'), ('cv_tailored', 'CV tailored'), ('applied', 'Applied'), ('assessment', 'Assessment'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], max_length=32)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-changed_at',),
            },
        ),
        migrations.AddField(
            model_name='userjob',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userjob',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userjob',
            index=models.Index(condition=models.Q(('reminder_sent_at__isnull', True)), fields=['remind_at'], name='userjob_pending_reminder'),
        ),
        migrations.AddField(
            model_name='userjobstatusevent',
            name='user_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.userjob'),
        ),
        migrations.AddIndex(
            model_name='userjobstatusevent',
            index=models.Index(fields=['user_job', '-changed_at'], name='statusevent_userjob_changed'),
        ),
    ]
