# Generated by Django 5.2.17 on 2026-08-15 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=dict, help_text='keyword → weight')),
                ('level_bonus', models.JSONField(default=dict, help_text='title term → multiplier')),
                ('level_penalty', models.JSONField(default=dict, help_text='title term → multiplier')),
                ('title_blocklist', models.JSONField(default=list)),
                ('locations_allowed', models.JSONField(default=list)),
                ('locations_preferred', models.JSONField(default=list)),
                ('locations_secondary', models.JSONField(default=list)),
                ('stack_saturation', models.FloatField(default=45.0)),
                ('freshness', models.JSONField(default=dict)),
                ('role_keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
